name: default

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install sparse

      - name: checkout
        uses: actions/checkout@v2

      - name: install meson, ninja
        run: pip install meson ninja

      - name: configure
        run: meson setup build

      - name: compile
        run: meson compile -C build

      - name: run sparse
        run: meson compile -C build sparse

      - name: upload log
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: meson log
          path: build/meson-logs/meson-log.txt
